swagger: "2.0"
info:
  version: "0.1 - 2015-12-10"
  title: "Retrieve player data of logged in users"
  description: "The player data web service will return responses in the 200 range when the requests can be handled successfully by the backend system. An error in the 400 range will occur if the service or if the backend system detect a functional error. An error in the 500 range will mean that there is an infrastructural     problem within the HC backend server landscape."
consumes:
  - application/json
produces:
  - application/json
paths:
  '/players/{username}':
    post:
      tags:
        - players
      summary: Get player data
      description:
        "Get data for the player with the given username. Service will check the validity of the combination of username and token. If valid, it will retrieve the user data. Returns an array of a single `Players` object."
      security:
        - token: []
      parameters:
        - in: header
          name: "Auth-Casino-Id"
          description: "Unique id of the casino the player is logged in to"
          required: true
          type: string
        - in: path
          name: username
          description: "Unique username"
          required: true
          type: string
      responses:
        '200':
          description: "OK - Player data found. Returns an array of a single `Players` object."
          schema:
            $ref: '#/definitions/players'
        '401':
          description: "Unauthorized - Invalid or no token."
        '404':
          description: "Not Found - No data found for specified username."
definitions:
  players:
    type: array
    items:
      properties:
        username:
          type: string
          description: "Unique username"
securityDefinitions:
  token:
    name: "Auth-Token"
    type: apiKey
    in: header
    description: "User token obtained from PlayTech"
